---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-legacyFile
spec:
    capacity:
      storage: 10Gi
    accessModes:
    - ReadWriteMany
    flexVolume:
      driver: hpe.com/hpe
      options:
        filePersona: ""
        fpg: <Legacy-FPG>
		
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-legacyFile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
	  
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-legacyFile
spec:
  containers:
  - name: minio
    securityContext:
      privileged: true
      capabilities:
        add: ["SYS_ADMIN"]
      allowPrivilegeEscalation: true
    image: minio/minio:latest
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: pvc-legacyFile	  
