---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-multicontainer
spec:
    capacity:
      storage: 35Gi
    accessModes:
    - ReadWriteOnce
    flexVolume:
      driver: hpe.com/hpe
      options:
        name: TEST

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-multicontainer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-multicontainer
spec:
  containers:
  - name: minio
    image: minio/minio:latest
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
  - name: nginx
    image: nginx
    volumeMounts:
    - name: export
      mountPath: /export
  restartPolicy: Always
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: pvc-multicontainer
